module.exports = {
    debugInfo: true,
    injectFileTypes: ["css", "png", "jpg", "jpeg", "svg", "gif", "webp"],
    minify: true,
    logConnections: false,
    host: null,
    ghostMode: {
        clicks: true,
        links: true,
        forms: true,
        scroll: true
    },
    server: false,
    proxy: false,
    ports: {
        min: 3000,
        max: 4000
    },
    open: true,
    xip: false,
    hostnameSuffix: false,
    notify: true,
    devMode: false,
    fileTimeout: 1000,
    scrollProportionally: true,
    scrollThrottle: 0,
    reloadDelay: 0,
    injectChanges: true,
    startPath: null,
    excludedFileTypes: [
        "js",
        "css",
        "pdf",
        "map",
        "svg",
        "ico",
        "woff",
        "json",
        "eot",
        "ttf",
        "png",
        "jpg",
        "jpeg",
        "webp",
        "gif",
        "mp4",
        "mp3",
        "3gp",
        "ogg",
        "ogv",
        "webm",
        "m4a",
        "flv",
        "wmv",
        "avi",
        "swf",
        "scss"
    ]
};