module.exports = {
    active: false,
    debugInfo: true,
    files: false,
    injectFileTypes: ["css", "png", "jpg", "jpeg", "svg", "gif", "webp"],
    minify: true,
    logConnections: false,
    host: null,
    codeSync: true,
    timestamps: true,
    ghostMode: {
        clicks: true,
        scroll: true,
        location: false,
        forms: {
            submit: true,
            inputs: true,
            toggles: true
        }
    },
    logLevel: "info",
    server: false,
    proxy: false,
    port: 3000,
    open: true,
    browser: "default",
    xip: false,
    hostnameSuffix: false,
    notify: true,
    devMode: false,
    debounce: 0,
    scrollProportionally: true,
    scrollThrottle: 0,
    reloadDelay: 0,
    injectChanges: true,
    startPath: null,
    excludedFileTypes: [
        "js",
        "css",
        "pdf",
        "map",
        "svg",
        "ico",
        "woff",
        "json",
        "eot",
        "ttf",
        "png",
        "jpg",
        "jpeg",
        "webp",
        "gif",
        "mp4",
        "mp3",
        "3gp",
        "ogg",
        "ogv",
        "webm",
        "m4a",
        "flv",
        "wmv",
        "avi",
        "swf",
        "scss"
    ]
};